version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: isodisplay-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-isodisplay}
      POSTGRES_USER: ${POSTGRES_USER:-isodisplay}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - isodisplay-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-isodisplay}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: isodisplay-app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-isodisplay}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-isodisplay}?schema=public
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3000}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NODE_ENV: production
    volumes:
      - uploads_data:/app/uploads
    ports:
      - "3000:3000"
    networks:
      - isodisplay-network

volumes:
  postgres_data:
    driver: local
  uploads_data:
    driver: local

networks:
  isodisplay-network:
    driver: bridge